USE [master]
GO

/****** Object:  Database [Clinic]    Script Date: 12.05.2019 01:58:35 ******/
DROP DATABASE [Clinic]
GO

/****** Object:  Database [Clinic]    Script Date: 12.05.2019 01:58:35 ******/
CREATE DATABASE [Clinic]
 CONTAINMENT = NONE
 /******ON  PRIMARY 
( NAME = N'Clinic', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\Clinic.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Clinic_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\Clinic_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
******/
GO

ALTER DATABASE [Clinic] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Clinic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Clinic] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Clinic] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Clinic] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Clinic] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Clinic] SET ARITHABORT OFF 
GO

ALTER DATABASE [Clinic] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Clinic] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Clinic] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Clinic] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Clinic] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Clinic] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Clinic] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Clinic] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Clinic] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Clinic] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Clinic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Clinic] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Clinic] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Clinic] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Clinic] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Clinic] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Clinic] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Clinic] SET RECOVERY FULL 
GO

ALTER DATABASE [Clinic] SET  MULTI_USER 
GO

ALTER DATABASE [Clinic] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Clinic] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Clinic] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Clinic] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Clinic] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Clinic] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Clinic] SET  READ_WRITE 
GO

